# Generated by Django 2.1.4 on 2019-01-16 07:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
                ('hash_password', models.CharField(blank=True, max_length=128, null=True, verbose_name='哈希密码')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女'), ('unknown', '未知')], default='未知', max_length=10, verbose_name='性别')),
                ('email', models.CharField(max_length=100, unique=True, verbose_name='邮箱')),
                ('register_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='注册日期')),
            ],
            options={
                'verbose_name': '用户表',
            },
        ),
    ]
